#!/bin/bash

#First Question
printf "First Algorithm IPC C++\nDimension\tReal Time\tProc Time\tTotal Instructions\tIPC\n"
for i in {500..3000..500}
	do
		printf "$i\t"
		./multMatrixIPC 1 $i
	done

printf "\n\nFirst Algorithm CACHE C++\nDimension\tReal Time\tProc Time\tTotal Instructions\tIPC\n"
for i in {500..3000..500}
	do 
		printf "$i\t"
		./multMatrixCache 1 $i
	done

printf "\n\nFirst Algorithm JAVA\nDimension\tReal Time\n"
for i in {500..3000..500}
        do 
		printf "$i\t"
                java MultMatrix 1 $i
        done

#Second Question
printf "\n\nSecond Algorithm IPC C++\nDimension\tReal Time\tProc Time\tTotal Instructions\tIPC\n"
for i in {500..3000..500}
        do 
		printf "$i\t"
                ./multMatrixIPC 2 $i
	done
for i in {5000..10000..1000}
        do
                printf "$i\t"
                ./multMatrixIPC 2 $i
        done

printf "\n\nSecond Algorithm CACHE C++\nDimension\tReal Time\tProc Time\tTotal Instructions\tIPC\n"
for i in {500..3000..500}
        do 
		printf "$i\t"
                ./multMatrixCache 2 $i
        done
for i in {5000..10000..1000}
        do
                printf "$i\t"
                ./multMatrixCache 2 $i
	done

#Third Question
printf "First Algorithm OpenMP IPC C++\nDimension\tN Threads\tReal Time\tProc Time\tTotal Instruction
s\tIPC\n"
for i in {500..3000..500}
        do
		for j in {1..8}
		do
	                printf "$i\t$j\t"
	                ./multMatrixIPC 3 $i $j 
		done
	done

printf "Second Algorithm OpenMP IPC C++\nDimension\tN Threads\tReal Time\tProc Time\
tTotal Instruction
s\tIPC\n"
for i in {500..3000..500}
        do
                for j in {1..8}
                do
                        printf "$i\t$j\t"
                        ./multMatrixIPC 4 $i $j
		done
	done
