#!/bin/bash
run="mpirun --hostfile hostfile -np"

printf "SE Execution\n\n"

#set -x

printf "Sequential\n"
for i in {100000000..600000000..100000000}
	do
		$run 1 se 1 teste.csv $i 0
		printf "\n"
	done

printf "\nOpenMP\n"
for i in {100000000..600000000..100000000}
	do
		$run 1 se 2 teste.csv $i 1
		printf "\n"
		$run 1 se 2 teste.csv $i 2
		printf "\n"
		$run 1 se 2 teste.csv $i 3
		printf "\n"
		$run 1 se 2 teste.csv $i 4
		printf "\n"
	done

printf "\nOpenMPI\n"
for i in {100000000..600000000..100000000}
	do
		$run 1 se 3 teste.csv $i 0
		printf "\n"
		$run 2 se 3 teste.csv $i 0
		printf "\n"
		$run 3 se 3 teste.csv $i 0
		printf "\n"
		$run 4 se 3 teste.csv $i 0
		printf "\n"
	done

	
printf "\n\nLU Execution\n\n"

printf "Sequential\n"
aux=1
for i in {1000..6000..1000}
	do
		$run 1 lu 1 matrix$aux.csv $i 0
		printf "\n"
		aux=$(($aux+1))
	done

aux=1
printf "\nOpenMP\n"
for i in {1000..6000..1000}
	do
		$run 1 lu 2 teste$aux.csv $i 1
		printf "\n"
		$run 1 lu 2 teste$aux.csv $i 2
		printf "\n"
		$run 1 lu 2 teste$aux.csv $i 3
		printf "\n"
		$run 1 lu 2 teste$aux.csv $i 4
		printf "\n"
		aux=$(($aux+1))
	done


aux=1
printf "\nOpenMPI\n"
for i in {1000..6000..1000}
	do
		$run 1 lu 3 teste$aux.csv $i 0
		printf "\n"
		$run 2 lu 3 teste$aux.csv $i 0
		printf "\n"
		$run 3 lu 3 teste$aux.csv $i 0
		printf "\n"
		$run 4 lu 3 teste$aux.csv $i 0
		printf "\n"
		aux=$(($aux+1))
	done
